#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/travel_compass
#    username: root
#    password: 200123704050A
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#application:
#  security:
#    jwt:
#      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
#      access-token-expiration: 86400000
#      refresh-token-expiration: 604800000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_compass
    username: root
    password: 200123704050A
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # Use 'update' to keep data between restarts
