#
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/travel_compass
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  properties:
#    hibernate:
#      format_sql: true
#
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 30MB
#
#  web:
#    resources:
#      static-locations: file:uploads/
#
#server:
#  port: 8081
#
#logging:
#  level:
#    root: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG




spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_compass
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  properties:
    hibernate:
      format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  web:
    resources:
      static-locations: file:./uploads/
      add-mappings: true

server:
  port: 8081

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
