


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_compass
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Use 'update' to keep data between restarts
    show-sql: true

  properties:
    hibernate:
      format_sql: true


server:
  port: 8081

  logging:
    level:
      root: DEBUG

      org.hibernate.SQL: DEBUG  # Show executed SQL queries
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Show SQL parameter values
      org.springframework.orm.jpa: DEBUG  # Show JPA debug logs
      org.springframework.transaction: DEBUG  # Show transaction logs